[[constraint]]
  name = "github.com/maruel/anim1d"
  version = "1.0.0"

[[constraint]]
  name = "github.com/maruel/interrupt"
  version = "1.0.1"

[[constraint]]
  name = "github.com/maruel/msgbus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/maruel/psf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/maruel/serve-dir"
  version = "1.0.1"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.2"

[[constraint]]
  name = "periph.io/x/periph"
  version = "2.0.0"
