// Code generated by "stringer -type Edge,Function,Pin,Pull -output string.go"; DO NOT EDIT

package bcm283x

import "fmt"

const _Edge_name = "EdgeNoneRisingFallingEdgeBoth"

var _Edge_index = [...]uint8{0, 8, 14, 21, 29}

func (i Edge) String() string {
	if i >= Edge(len(_Edge_index)-1) {
		return fmt.Sprintf("Edge(%d)", i)
	}
	return _Edge_name[_Edge_index[i]:_Edge_index[i+1]]
}

const _Function_name = "InOutAlt5Alt4Alt0Alt1Alt2Alt3"

var _Function_index = [...]uint8{0, 2, 5, 9, 13, 17, 21, 25, 29}

func (i Function) String() string {
	if i >= Function(len(_Function_index)-1) {
		return fmt.Sprintf("Function(%d)", i)
	}
	return _Function_name[_Function_index[i]:_Function_index[i+1]]
}

const (
	_Pin_name_0 = "GPIO0GPIO1GPIO2GPIO3GPIO4GPIO5GPIO6GPIO7GPIO8GPIO9GPIO10GPIO11GPIO12GPIO13GPIO14GPIO15GPIO16GPIO17GPIO18GPIO19GPIO20GPIO21GPIO22GPIO23GPIO24GPIO25GPIO26GPIO27GPIO28GPIO29GPIO30GPIO31GPIO32GPIO33GPIO34GPIO35GPIO36GPIO37GPIO38GPIO39GPIO40GPIO41GPIO42GPIO43GPIO44GPIO45GPIO46GPIO47GPIO48GPIO49GPIO50GPIO51GPIO52GPIO53"
	_Pin_name_1 = "V5V3_3GROUNDINVALID"
)

var (
	_Pin_index_0 = [...]uint16{0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 56, 62, 68, 74, 80, 86, 92, 98, 104, 110, 116, 122, 128, 134, 140, 146, 152, 158, 164, 170, 176, 182, 188, 194, 200, 206, 212, 218, 224, 230, 236, 242, 248, 254, 260, 266, 272, 278, 284, 290, 296, 302, 308, 314}
	_Pin_index_1 = [...]uint8{0, 2, 6, 12, 19}
)

func (i Pin) String() string {
	switch {
	case 0 <= i && i <= 53:
		return _Pin_name_0[_Pin_index_0[i]:_Pin_index_0[i+1]]
	case 252 <= i && i <= 255:
		i -= 252
		return _Pin_name_1[_Pin_index_1[i]:_Pin_index_1[i+1]]
	default:
		return fmt.Sprintf("Pin(%d)", i)
	}
}

const _Pull_name = "FloatDownUpPullNoChange"

var _Pull_index = [...]uint8{0, 5, 9, 11, 23}

func (i Pull) String() string {
	if i >= Pull(len(_Pull_index)-1) {
		return fmt.Sprintf("Pull(%d)", i)
	}
	return _Pull_name[_Pull_index[i]:_Pull_index[i+1]]
}
