// Code generated by "stringer -type QOS"; DO NOT EDIT

package modules

import "fmt"

const _QOS_name = "BestEffortMinOnceExactlyOnce"

var _QOS_index = [...]uint8{0, 10, 17, 28}

func (i QOS) String() string {
	if i < 0 || i >= QOS(len(_QOS_index)-1) {
		return fmt.Sprintf("QOS(%d)", i)
	}
	return _QOS_name[_QOS_index[i]:_QOS_index[i+1]]
}
