/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev */

#include "config.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Wifi_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, Wifi, ssid, ssid, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, Wifi, password, ssid, 0),
    PB_LAST_FIELD
};

const pb_field_t Config_fields[6] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, Config, wifiClient, wifiClient, &Wifi_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, Config, wifiAP, wifiClient, &Wifi_fields),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, Config, romURL, wifiAP, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, Config, name, romURL, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, Config, highSpeed, name, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Config, wifiClient) < 65536 && pb_membersize(Config, wifiAP) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Wifi_Config)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Config, wifiClient) < 256 && pb_membersize(Config, wifiAP) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Wifi_Config)
#endif


/* @@protoc_insertion_point(eof) */
