// Copyright 2016 Marc-Antoine Ruel. All rights reserved.
// Use of this source code is governed under the Apache License, Version 2.0
// that can be found in the LICENSE file.

// Package bcm283x exposes all BCM283x GPIO functionality, including pull
// resistors and edge triggered interupts.
//
// Internals
//
// It leverages Raspbian's /dev/giomem for all access except for edge based
// triggering, which uses gpio sysfs as it requires kernel cooperation to
// handle the interrupts generated by the CPU.
//
// When a pin is used as input with a edge value other than EdgeNone, gpio
// sysfs is used to read the value via interrupts. Otherwise, the value is read
// directly from memory, which is very fast, much faster than having to read
// from a file handle.
//
// If only EdgeNone is used, gpio sysfs is not used.
//
// This library cannot work without /dev/gpiomem. It could be rewritten to use
// /dev/mem but that requires running as root and defeats all security.
//
// The downside of gpio sysfs, beside performance, is that it does not expose
// the internal pull resistors (pull-up, pull-down). The only way to set them
// is via /dev/gpiomem.
//
// Datasheet
//
// https://www.raspberrypi.org/wp-content/uploads/2012/02/BCM2835-ARM-Peripherals.pdf
package bcm283x
