/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev */

#include "anim1d_msg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t MColor_color_default = 0u;


const pb_field_t MColor_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MColor, color, color, &MColor_color_default),
    PB_LAST_FIELD
};

const pb_field_t MFrame_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, MFrame, colors, colors, 0),
    PB_LAST_FIELD
};

const pb_field_t MRainbow_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t MRepeated_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, MRepeated, frame, frame, &MFrame_fields),
    PB_LAST_FIELD
};

const pb_field_t MPattern_fields[5] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, MPattern, color, color, &MColor_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, MPattern, frame, color, &MFrame_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, MPattern, rainbow, frame, &MRainbow_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, MPattern, repeat, rainbow, &MRepeated_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MRepeated, frame) < 65536 && pb_membersize(MPattern, color) < 65536 && pb_membersize(MPattern, frame) < 65536 && pb_membersize(MPattern, rainbow) < 65536 && pb_membersize(MPattern, repeat) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MColor_MFrame_MRainbow_MRepeated_MPattern)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MRepeated, frame) < 256 && pb_membersize(MPattern, color) < 256 && pb_membersize(MPattern, frame) < 256 && pb_membersize(MPattern, rainbow) < 256 && pb_membersize(MPattern, repeat) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MColor_MFrame_MRainbow_MRepeated_MPattern)
#endif


/* @@protoc_insertion_point(eof) */
