// Code generated by "stringer -type Function"; DO NOT EDIT

package rpi

import "fmt"

const _Function_name = "InOutAlt5Alt4Alt0Alt1Alt2Alt3"

var _Function_index = [...]uint8{0, 2, 5, 9, 13, 17, 21, 25, 29}

func (i Function) String() string {
	if i >= Function(len(_Function_index)-1) {
		return fmt.Sprintf("Function(%d)", i)
	}
	return _Function_name[_Function_index[i]:_Function_index[i+1]]
}
