// Code generated by "stringer -type Edge"; DO NOT EDIT

package rpi

import "fmt"

const _Edge_name = "EdgeNoneRisingFallingEdgeBoth"

var _Edge_index = [...]uint8{0, 8, 14, 21, 29}

func (i Edge) String() string {
	if i >= Edge(len(_Edge_index)-1) {
		return fmt.Sprintf("Edge(%d)", i)
	}
	return _Edge_name[_Edge_index[i]:_Edge_index[i+1]]
}
