// Code generated by "stringer -type Pull"; DO NOT EDIT

package rpi

import "fmt"

const _Pull_name = "FloatDownUp"

var _Pull_index = [...]uint8{0, 5, 9, 11}

func (i Pull) String() string {
	if i >= Pull(len(_Pull_index)-1) {
		return fmt.Sprintf("Pull(%d)", i)
	}
	return _Pull_name[_Pull_index[i]:_Pull_index[i+1]]
}
